{% set name = "pyquickhelper" %}
{% set version = "1.11.3697" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyquickhelper-{{ version }}.tar.gz
  sha256: b0a2ff448c1feedbff820fffdb05129ad890c89f4aef787b133944d1cc175326

build:
  number: 0
  noarch: python
  entry_points:
    - encrypt = pyquickhelper.cli.encryption_cli:encrypt
    - decrypt = pyquickhelper.cli.encryption_cli:decrypt
    - encrypt_file = pyquickhelper.cli.encryption_file_cli:encrypt_file
    - decrypt_file = pyquickhelper.cli.encryption_file_cli:decrypt_file
    - pyq-sync = pyquickhelper.cli.pyq_sync_cli:pyq_sync
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pyquicksetup
    - python >=3.6
  run:
    - fire
    - numpy >=1.16.0
    - pyquicksetup >=0.2
    - python >=3.6

test:
  imports:
    - pyquickhelper
    - pyquickhelper.benchhelper
  commands:
    - pip check
    - encrypt --help
    - decrypt --help
    - encrypt_file --help
    - decrypt_file --help
    # - pyq-sync --help  # currently broken: https://github.com/sdpython/pyquickhelper/issues/340
  requires:
    - pip

about:
  home: http://www.xavierdupre.fr/app/pyquickhelper/helpsphinx/index.html
  summary: Various automations in Python.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - janjagusch
